// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: dropboxsync.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SyncConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key         string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Origin      string `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *SyncConfig) Reset() {
	*x = SyncConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropboxsync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncConfig) ProtoMessage() {}

func (x *SyncConfig) ProtoReflect() protoreflect.Message {
	mi := &file_dropboxsync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncConfig.ProtoReflect.Descriptor instead.
func (*SyncConfig) Descriptor() ([]byte, []int) {
	return file_dropboxsync_proto_rawDescGZIP(), []int{0}
}

func (x *SyncConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SyncConfig) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *SyncConfig) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CoreKey     string        `protobuf:"bytes,1,opt,name=core_key,json=coreKey,proto3" json:"core_key,omitempty"` // NOT NEEDED
	SyncConfigs []*SyncConfig `protobuf:"bytes,2,rep,name=sync_configs,json=syncConfigs,proto3" json:"sync_configs,omitempty"`
}

func (x *Config) Reset() {
	*x = Config{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropboxsync_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_dropboxsync_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_dropboxsync_proto_rawDescGZIP(), []int{1}
}

func (x *Config) GetCoreKey() string {
	if x != nil {
		return x.CoreKey
	}
	return ""
}

func (x *Config) GetSyncConfigs() []*SyncConfig {
	if x != nil {
		return x.SyncConfigs
	}
	return nil
}

type AddSyncConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToAdd *SyncConfig `protobuf:"bytes,1,opt,name=to_add,json=toAdd,proto3" json:"to_add,omitempty"`
}

func (x *AddSyncConfigRequest) Reset() {
	*x = AddSyncConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropboxsync_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSyncConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSyncConfigRequest) ProtoMessage() {}

func (x *AddSyncConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dropboxsync_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSyncConfigRequest.ProtoReflect.Descriptor instead.
func (*AddSyncConfigRequest) Descriptor() ([]byte, []int) {
	return file_dropboxsync_proto_rawDescGZIP(), []int{2}
}

func (x *AddSyncConfigRequest) GetToAdd() *SyncConfig {
	if x != nil {
		return x.ToAdd
	}
	return nil
}

type AddSyncConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddSyncConfigResponse) Reset() {
	*x = AddSyncConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dropboxsync_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddSyncConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddSyncConfigResponse) ProtoMessage() {}

func (x *AddSyncConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dropboxsync_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddSyncConfigResponse.ProtoReflect.Descriptor instead.
func (*AddSyncConfigResponse) Descriptor() ([]byte, []int) {
	return file_dropboxsync_proto_rawDescGZIP(), []int{3}
}

var File_dropboxsync_proto protoreflect.FileDescriptor

var file_dropboxsync_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x72, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x72, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x73, 0x79, 0x6e, 0x63,
	0x22, 0x58, 0x0a, 0x0a, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x16, 0x0a, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x5f, 0x0a, 0x06, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x12,
	0x3a, 0x0a, 0x0c, 0x73, 0x79, 0x6e, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x73,
	0x79, 0x6e, 0x63, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0b,
	0x73, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x73, 0x22, 0x46, 0x0a, 0x14, 0x41,
	0x64, 0x64, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x73, 0x79, 0x6e,
	0x63, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x05, 0x74, 0x6f,
	0x41, 0x64, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x6e, 0x0a, 0x12,
	0x44, 0x72, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x58, 0x0a, 0x0d, 0x41, 0x64, 0x64, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x21, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x73, 0x79, 0x6e,
	0x63, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x72, 0x6f, 0x70, 0x62, 0x6f, 0x78,
	0x73, 0x79, 0x6e, 0x63, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2b, 0x5a, 0x29,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x62, 0x72, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x6c, 0x6f, 0x67, 0x69, 0x63, 0x2f, 0x64, 0x72, 0x6f, 0x70, 0x62, 0x6f, 0x78, 0x73,
	0x79, 0x6e, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_dropboxsync_proto_rawDescOnce sync.Once
	file_dropboxsync_proto_rawDescData = file_dropboxsync_proto_rawDesc
)

func file_dropboxsync_proto_rawDescGZIP() []byte {
	file_dropboxsync_proto_rawDescOnce.Do(func() {
		file_dropboxsync_proto_rawDescData = protoimpl.X.CompressGZIP(file_dropboxsync_proto_rawDescData)
	})
	return file_dropboxsync_proto_rawDescData
}

var file_dropboxsync_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dropboxsync_proto_goTypes = []interface{}{
	(*SyncConfig)(nil),            // 0: dropboxsync.SyncConfig
	(*Config)(nil),                // 1: dropboxsync.Config
	(*AddSyncConfigRequest)(nil),  // 2: dropboxsync.AddSyncConfigRequest
	(*AddSyncConfigResponse)(nil), // 3: dropboxsync.AddSyncConfigResponse
}
var file_dropboxsync_proto_depIdxs = []int32{
	0, // 0: dropboxsync.Config.sync_configs:type_name -> dropboxsync.SyncConfig
	0, // 1: dropboxsync.AddSyncConfigRequest.to_add:type_name -> dropboxsync.SyncConfig
	2, // 2: dropboxsync.DropboxSyncService.AddSyncConfig:input_type -> dropboxsync.AddSyncConfigRequest
	3, // 3: dropboxsync.DropboxSyncService.AddSyncConfig:output_type -> dropboxsync.AddSyncConfigResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dropboxsync_proto_init() }
func file_dropboxsync_proto_init() {
	if File_dropboxsync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dropboxsync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dropboxsync_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Config); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dropboxsync_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSyncConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dropboxsync_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddSyncConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dropboxsync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dropboxsync_proto_goTypes,
		DependencyIndexes: file_dropboxsync_proto_depIdxs,
		MessageInfos:      file_dropboxsync_proto_msgTypes,
	}.Build()
	File_dropboxsync_proto = out.File
	file_dropboxsync_proto_rawDesc = nil
	file_dropboxsync_proto_goTypes = nil
	file_dropboxsync_proto_depIdxs = nil
}
