// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dropboxsync.proto

package dropboxsync

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SyncConfig struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Origin               string   `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination          string   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncConfig) Reset()         { *m = SyncConfig{} }
func (m *SyncConfig) String() string { return proto.CompactTextString(m) }
func (*SyncConfig) ProtoMessage()    {}
func (*SyncConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_e581dd35db418eb0, []int{0}
}

func (m *SyncConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncConfig.Unmarshal(m, b)
}
func (m *SyncConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncConfig.Marshal(b, m, deterministic)
}
func (m *SyncConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncConfig.Merge(m, src)
}
func (m *SyncConfig) XXX_Size() int {
	return xxx_messageInfo_SyncConfig.Size(m)
}
func (m *SyncConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SyncConfig proto.InternalMessageInfo

func (m *SyncConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SyncConfig) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *SyncConfig) GetDestination() string {
	if m != nil {
		return m.Destination
	}
	return ""
}

type Config struct {
	CoreKey              string        `protobuf:"bytes,1,opt,name=core_key,json=coreKey,proto3" json:"core_key,omitempty"`
	SyncConfigs          []*SyncConfig `protobuf:"bytes,2,rep,name=sync_configs,json=syncConfigs,proto3" json:"sync_configs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_e581dd35db418eb0, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetCoreKey() string {
	if m != nil {
		return m.CoreKey
	}
	return ""
}

func (m *Config) GetSyncConfigs() []*SyncConfig {
	if m != nil {
		return m.SyncConfigs
	}
	return nil
}

type UpdateConfigRequest struct {
	NewCoreKey           string   `protobuf:"bytes,1,opt,name=new_core_key,json=newCoreKey,proto3" json:"new_core_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigRequest) Reset()         { *m = UpdateConfigRequest{} }
func (m *UpdateConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigRequest) ProtoMessage()    {}
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e581dd35db418eb0, []int{2}
}

func (m *UpdateConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigRequest.Unmarshal(m, b)
}
func (m *UpdateConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigRequest.Merge(m, src)
}
func (m *UpdateConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigRequest.Size(m)
}
func (m *UpdateConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigRequest proto.InternalMessageInfo

func (m *UpdateConfigRequest) GetNewCoreKey() string {
	if m != nil {
		return m.NewCoreKey
	}
	return ""
}

type UpdateConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateConfigResponse) Reset()         { *m = UpdateConfigResponse{} }
func (m *UpdateConfigResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateConfigResponse) ProtoMessage()    {}
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e581dd35db418eb0, []int{3}
}

func (m *UpdateConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConfigResponse.Unmarshal(m, b)
}
func (m *UpdateConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConfigResponse.Marshal(b, m, deterministic)
}
func (m *UpdateConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConfigResponse.Merge(m, src)
}
func (m *UpdateConfigResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateConfigResponse.Size(m)
}
func (m *UpdateConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConfigResponse proto.InternalMessageInfo

type AddSyncConfigRequest struct {
	ToAdd                *SyncConfig `protobuf:"bytes,1,opt,name=to_add,json=toAdd,proto3" json:"to_add,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddSyncConfigRequest) Reset()         { *m = AddSyncConfigRequest{} }
func (m *AddSyncConfigRequest) String() string { return proto.CompactTextString(m) }
func (*AddSyncConfigRequest) ProtoMessage()    {}
func (*AddSyncConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e581dd35db418eb0, []int{4}
}

func (m *AddSyncConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSyncConfigRequest.Unmarshal(m, b)
}
func (m *AddSyncConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSyncConfigRequest.Marshal(b, m, deterministic)
}
func (m *AddSyncConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSyncConfigRequest.Merge(m, src)
}
func (m *AddSyncConfigRequest) XXX_Size() int {
	return xxx_messageInfo_AddSyncConfigRequest.Size(m)
}
func (m *AddSyncConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSyncConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddSyncConfigRequest proto.InternalMessageInfo

func (m *AddSyncConfigRequest) GetToAdd() *SyncConfig {
	if m != nil {
		return m.ToAdd
	}
	return nil
}

type AddSyncConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddSyncConfigResponse) Reset()         { *m = AddSyncConfigResponse{} }
func (m *AddSyncConfigResponse) String() string { return proto.CompactTextString(m) }
func (*AddSyncConfigResponse) ProtoMessage()    {}
func (*AddSyncConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e581dd35db418eb0, []int{5}
}

func (m *AddSyncConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddSyncConfigResponse.Unmarshal(m, b)
}
func (m *AddSyncConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddSyncConfigResponse.Marshal(b, m, deterministic)
}
func (m *AddSyncConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddSyncConfigResponse.Merge(m, src)
}
func (m *AddSyncConfigResponse) XXX_Size() int {
	return xxx_messageInfo_AddSyncConfigResponse.Size(m)
}
func (m *AddSyncConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddSyncConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddSyncConfigResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SyncConfig)(nil), "dropboxsync.SyncConfig")
	proto.RegisterType((*Config)(nil), "dropboxsync.Config")
	proto.RegisterType((*UpdateConfigRequest)(nil), "dropboxsync.UpdateConfigRequest")
	proto.RegisterType((*UpdateConfigResponse)(nil), "dropboxsync.UpdateConfigResponse")
	proto.RegisterType((*AddSyncConfigRequest)(nil), "dropboxsync.AddSyncConfigRequest")
	proto.RegisterType((*AddSyncConfigResponse)(nil), "dropboxsync.AddSyncConfigResponse")
}

func init() { proto.RegisterFile("dropboxsync.proto", fileDescriptor_e581dd35db418eb0) }

var fileDescriptor_e581dd35db418eb0 = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0x05, 0x62, 0xd5, 0x29, 0x26, 0x3a, 0x22, 0x54, 0x4e, 0x75, 0x4f, 0x9c, 0x7a, 0xc0,
	0x83, 0x89, 0x37, 0x82, 0xf1, 0xe2, 0x0d, 0x42, 0xc2, 0xad, 0x29, 0xdd, 0x91, 0x6c, 0x4c, 0x76,
	0x6a, 0x77, 0x15, 0xfb, 0x01, 0xfd, 0x5e, 0xa6, 0x7f, 0x94, 0x96, 0x90, 0xde, 0x76, 0xfe, 0xfd,
	0xde, 0x7b, 0xc9, 0xc2, 0xb5, 0x4c, 0x39, 0xd9, 0xf0, 0xb7, 0xc9, 0x74, 0x1c, 0x24, 0x29, 0x5b,
	0x46, 0xb7, 0xd6, 0x12, 0x6b, 0x80, 0x65, 0xa6, 0xe3, 0x39, 0xeb, 0x37, 0xb5, 0xc5, 0x2b, 0xe8,
	0xbd, 0x53, 0xe6, 0x75, 0xfc, 0xce, 0xe4, 0x62, 0x91, 0x3f, 0x71, 0x08, 0x0e, 0xa7, 0x6a, 0xab,
	0xb4, 0xd7, 0x2d, 0x9a, 0x55, 0x85, 0x3e, 0xb8, 0x92, 0x8c, 0x55, 0x3a, 0xb2, 0x8a, 0xb5, 0xd7,
	0x2b, 0x86, 0xf5, 0x96, 0x08, 0xc1, 0xa9, 0xa8, 0x77, 0x70, 0x1e, 0x73, 0x4a, 0xe1, 0x1e, 0x7d,
	0x96, 0xd7, 0xaf, 0x94, 0xe1, 0x13, 0xf4, 0x73, 0x1b, 0x61, 0x5c, 0x6c, 0x1a, 0xaf, 0xeb, 0xf7,
	0x26, 0xee, 0x74, 0x14, 0xd4, 0x5d, 0xef, 0xfd, 0x2d, 0x5c, 0xf3, 0xff, 0x36, 0xe2, 0x11, 0x6e,
	0x56, 0x89, 0x8c, 0x2c, 0x55, 0x43, 0xfa, 0xf8, 0x24, 0x63, 0xd1, 0x87, 0xbe, 0xa6, 0x5d, 0x78,
	0xa0, 0x08, 0x9a, 0x76, 0xf3, 0x52, 0x54, 0x0c, 0x61, 0xd0, 0x3c, 0x34, 0x09, 0x6b, 0x43, 0xe2,
	0x05, 0x06, 0x33, 0x29, 0x6b, 0x72, 0x15, 0x31, 0x00, 0xc7, 0x72, 0x18, 0x49, 0x59, 0xb0, 0x5a,
	0xec, 0x9d, 0x5a, 0x9e, 0x49, 0x29, 0x46, 0x70, 0x7b, 0xc0, 0x29, 0x05, 0xa6, 0x3f, 0x1d, 0xc0,
	0xe7, 0xf2, 0x34, 0x9f, 0x2e, 0x29, 0xfd, 0x52, 0x31, 0xe1, 0x0a, 0xfa, 0x75, 0x3f, 0xe8, 0x37,
	0xf8, 0x47, 0x32, 0x8e, 0xef, 0x5b, 0x36, 0xaa, 0x30, 0x27, 0xb8, 0x86, 0xcb, 0x86, 0x0d, 0x6c,
	0x5e, 0x1d, 0x8b, 0x3a, 0x16, 0x6d, 0x2b, 0x7f, 0xe4, 0x8d, 0x53, 0x7c, 0xa4, 0x87, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb1, 0x67, 0xdc, 0x71, 0x5d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DropboxSyncServiceClient is the client API for DropboxSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DropboxSyncServiceClient interface {
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	AddSyncConfig(ctx context.Context, in *AddSyncConfigRequest, opts ...grpc.CallOption) (*AddSyncConfigResponse, error)
}

type dropboxSyncServiceClient struct {
	cc *grpc.ClientConn
}

func NewDropboxSyncServiceClient(cc *grpc.ClientConn) DropboxSyncServiceClient {
	return &dropboxSyncServiceClient{cc}
}

func (c *dropboxSyncServiceClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, "/dropboxsync.DropboxSyncService/UpdateConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dropboxSyncServiceClient) AddSyncConfig(ctx context.Context, in *AddSyncConfigRequest, opts ...grpc.CallOption) (*AddSyncConfigResponse, error) {
	out := new(AddSyncConfigResponse)
	err := c.cc.Invoke(ctx, "/dropboxsync.DropboxSyncService/AddSyncConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DropboxSyncServiceServer is the server API for DropboxSyncService service.
type DropboxSyncServiceServer interface {
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	AddSyncConfig(context.Context, *AddSyncConfigRequest) (*AddSyncConfigResponse, error)
}

func RegisterDropboxSyncServiceServer(s *grpc.Server, srv DropboxSyncServiceServer) {
	s.RegisterService(&_DropboxSyncService_serviceDesc, srv)
}

func _DropboxSyncService_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropboxSyncServiceServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dropboxsync.DropboxSyncService/UpdateConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropboxSyncServiceServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DropboxSyncService_AddSyncConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSyncConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DropboxSyncServiceServer).AddSyncConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dropboxsync.DropboxSyncService/AddSyncConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DropboxSyncServiceServer).AddSyncConfig(ctx, req.(*AddSyncConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DropboxSyncService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dropboxsync.DropboxSyncService",
	HandlerType: (*DropboxSyncServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateConfig",
			Handler:    _DropboxSyncService_UpdateConfig_Handler,
		},
		{
			MethodName: "AddSyncConfig",
			Handler:    _DropboxSyncService_AddSyncConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dropboxsync.proto",
}
